### ISSUE TITLE
[BE] GitHub OAuth2 서버구축과 연동을 구현한다.

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-member-2020/sidedish-10#21]
* 다음의 공식문서를 잘 따라해본다.
링크: https://spring.io/guides/tutorials/spring-boot-oauth2/
* JWT 토큰과 함께 구현한다.

**Comment by realsigridjin** [comment]
## 궁금증 모음
* https://javabeat.net/spring-mvc-requestparam-pathvariable/
* https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-5.-%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%9D%B8%EC%A6%9D-%EB%B0%A9%EC%8B%9D-%EA%B2%B0%EC%A0%95
* LinkedMultiValueMap에 대해 학습한다.
* 자바 와일드카드에 대해 학습한다.

**Comment by realsigridjin** [comment]
## 스프링부트 리다이렉트는 이렇게
```
@Controller
public class WelcomeController {
 
    @GetMapping("/")
    public RedirectView index() {
        return new RedirectView("/apidocs/index.html");
    }
}
* https://jojoldu.tistory.com/478
* https://aramk.tistory.com/33
* https://stackoverflow.com/questions/10358345/making-authenticated-post-requests-with-spring-resttemplate-for-android
* https://jojoldu.tistory.com/341
* https://eblo.tistory.com/72

```
## Content-Type
* 지금 요청이 어떤 Type인지 지정하는 것이다.
