### ISSUE TITLE
[BE] 재고 상태를 처리하는 테이블을 추가로 생성한다.

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-member-2020/sidedish-10#43]
➎주문하기 버튼을 누르면 해당 상품에 대한 주문을 요청하고, 주문이 성공하면 이전 화면으로 되돌아 간다.
만약 재고가 부족하거나 주문이 불가능한 상품인 경우는 에러 코드에 맞는 안내 화면을 표시해야 한다.

**Comment by realsigridjin** [comment]
1. 일단, 매번마다 새롭게 파싱하지 않도록 DROP TABLE EXISTS를 수정한다. 왜냐하면 Mock API에는 그러한 데이터가 없기 때문이다.
* 다음의 키워드를 이용한다. ```CREATE TABLE IF NOT EXISTS```
