### ISSUE TITLE
[BE] nginx 프론트 배포 준비

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-member-2020/sidedish-10#48]
# 당일 프론트 배포 준비

백엔드 금일 작업상황 안내 (16시까지, 아래는 우선순위 순으로 정렬)
- [x] 프론트 배포 테스트(Nginx)
- [x] 리버스 프록시 설정 (8080 포트 to 80 포트)
- [x] 이미지 겹치는 문제 확인하기
- [x] 주문하기 API 작업하기
- [ ] JWT 토큰 프론트 로그인 확인하기

**Comment by realsigridjin** [comment]
리버스 프록시 설정: https://gist.github.com/jypthemiracle/39967db32a3e91e7b82176316255f17c

**Comment by realsigridjin** [comment]
모두 코드스쿼드 Mock API가 문제였음 -_-
- [x] 이미지 겹치는 문제 확인하기
- [x] 주문하기 API 작업하기
